name: Automerge

on:
  push:
  pull_request:

jobs:


  Pipeline:
    if: ${{ !(github.event_name != 'pull_request' && github.actor == 'dependabot[bot]') }}
    uses: ./.github/workflows/Tests.yml


  Automerge:
    needs: Pipeline
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Automerge dependabot PRs
    permissions:
      contents: write

    steps:

      - name: Auto-merge Dependabot PR
        run: GITHUB_TOKEN='${{ github.token }}' gh pr merge '${{ github.event.pull_request.html_url }}' --squash


  Check-statuses:
    needs: Pipeline
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v3

      - name: 🐍 Install Python requirements
        run: pip install PyGithub git+https://github.com/SymbiFlow/symbiflow-tools-data-manager#egg=stdm --progress-bar off

      - name: '🚧 Check Status'
        run: ./.github/scripts/check-status.py
        id: check
        env:
          GITHUB_REPOSITORY: ${{ github.repo }}
          INPUT_TOKEN: ${{ github.token }}
          INPUT_SHA: ${{ github.event.sha }}

      - name: '🚀 Upload artifact URL file'
        if: steps.check.outputs.skip != 'true'
        uses: weslenng/gcp-storage-sync@master
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
          GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
          SOURCE_DIR: "install"
