name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-18.04
    steps:

    - name: Setup
      run: |
        echo "::group::Current ~/.gitconfig"
        cat ~/.gitconfig || true
        echo "::endgroup::"

        # We need to setup git-lfs so that after we remove it, git-lfs usage
        # will cause failure.
        echo "::group::Setup git-lfs"
        git lfs install
        cat ~/.gitconfig || true
        echo "::endgroup::"

        echo "::group::Remove git-lfs"
        which git-lfs || true
        sudo apt-get remove -y git-lfs
        which git-lfs || true
        echo "::endgroup::"

        echo "::group::Final ~/.gitconfig"
        cat ~/.gitconfig || true
        echo "::endgroup::"

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: false
        submodules: false

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install git g++-6 colordiff coreutils graphviz inkscape make cmake

    - name: Execute test script
      run: stdbuf -i0 -o0 -e0 ./.github/ci/test.sh
