name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-18.04
    steps:

    - name: Setup
      run: |
        which git-lfs || true
        sudo apt-get remove -y git-lfs
        which git-lfs || true

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install git g++-6 colordiff coreutils graphviz inkscape make cmake

    - name: Execute test script
      run: stdbuf -i0 -o0 -e0 ./.github/ci/test.sh
