name: py4FPGA

on:
  push:
  pull_request:

jobs:


  Test-pip:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - uses: actions/checkout@v2
#        with:
#          submodules: recursive

      - name: Build pyFPGA
        run: |
          cd f4pga
          pip install .

      - name: Test py4FPGA
        run: |
          f4pga
          f4pga -h


  Test-PYTHONPATH:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - uses: actions/checkout@v2
#        with:
#          submodules: recursive

      - name: Test py4FPGA (PYTHONPATH)
        run: |
          PYTHONPATH=$(pwd) python3 f4pga/sfbuild.py
          PYTHONPATH=$(pwd) python3 f4pga/sfbuild.py -h
